"""Rollback-only TEST E2E for V0.4 capital, cash skip, and settlement."""
from __future__ import annotations

import json
import sys
from datetime import datetime
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from dotenv import load_dotenv
from src.daily_ma_v03.capital import AvailableCash, SettlementAmounts
from src.daily_ma_v03.capital_repository import PostgresDailyMaCapitalStore
from src.daily_ma_v03.capital_runtime import DailyMaV04CapitalNoSendRuntime
from src.repository.database import DatabaseSettings


class _SharedTransaction:
    def __init__(self, connection): self.connection = connection
    def __enter__(self): return self.connection
    def __exit__(self, *_): return False


def main() -> int:
    load_dotenv(ROOT / ".env")
    settings = DatabaseSettings.from_environment()
    if settings.name != "trading_system_v2_test":
        raise SystemExit("fixture is restricted to trading_system_v2_test")
    import psycopg
    with psycopg.connect(**settings.connection_kwargs()) as connection:
        connection.execute("BEGIN")
        with connection.cursor() as cursor:
            cursor.execute("""SELECT p.paper_trade_id,p.strategy_id,m.execution_code,o.operation_id
                                FROM daily_strategy_paper_trade p
                                JOIN daily_strategy_master m USING(strategy_id)
                                JOIN daily_strategy_operation o USING(strategy_id)
                               WHERE m.strategy_role='CANONICAL' AND p.source_system='DAILY_MA_V03'
                               ORDER BY p.paper_trade_id LIMIT 1""")
            paper_trade_id, strategy_id, stock, operation_id = cursor.fetchone()
            cursor.execute("""INSERT INTO daily_strategy_compound_capital
                              (strategy_id,capital_epoch_no,source_operation_id,epoch_initial_capital,strategy_compound_capital)
                              VALUES (%s,1,%s,1000,1000)""", (strategy_id, operation_id))
        factory = lambda: _SharedTransaction(connection)
        store = PostgresDailyMaCapitalStore(factory, commit=False)
        runtime = DailyMaV04CapitalNoSendRuntime(capital_store=store)
        base = dict(paper_trade_id=int(paper_trade_id), strategy_id=str(strategy_id), execution_stock_code=str(stock),
                    strategy_instance_id=f"DAILY_MA_{strategy_id}", reference_price=Decimal("100"),
                    signal_time=datetime(2026, 8, 24, 15, 18), execution_target_time=datetime(2026, 8, 24, 15, 19),
                    capital_epoch_no=1, operation_status="LIVE", reconciliation_healthy=True)
        cash = AvailableCash(Decimal("1000"), includes_pending_order_reservations=True)
        first = runtime.plan_entry(**base, signal_event_key="V04_E2E_ENTRY_A", available_cash=cash)
        restart = DailyMaV04CapitalNoSendRuntime(capital_store=PostgresDailyMaCapitalStore(factory, commit=False))
        duplicate = restart.plan_entry(**base, signal_event_key="V04_E2E_ENTRY_A", available_cash=cash)
        second = runtime.plan_entry(**base, signal_event_key="V04_E2E_ENTRY_B", available_cash=cash)
        skip = runtime.plan_entry(**base, signal_event_key="V04_E2E_SKIP", available_cash=AvailableCash(Decimal("99"), True))
        skip_retry = restart.plan_entry(**base, signal_event_key="V04_E2E_SKIP", available_cash=cash)
        with connection.cursor() as cursor:
            cursor.execute("""SELECT count(*) FROM daily_strategy_live_order_intent
                               WHERE signal_event_key LIKE 'V04_E2E_%'""")
            intents = cursor.fetchone()[0]
            cursor.execute("""SELECT count(*) FROM daily_strategy_live_capital_reservation r
                               JOIN daily_strategy_live_order_intent i USING(intent_id)
                              WHERE i.signal_event_key LIKE 'V04_E2E_%'""")
            reservations = cursor.fetchone()[0]
            cursor.execute("SELECT count(*) FROM daily_strategy_live_entry_skip WHERE signal_event_key LIKE 'V04_E2E_%'")
            skips = cursor.fetchone()[0]
            # No actual broker objects are ever generated by this fixture.
            cursor.execute("SELECT count(*) FROM daily_strategy_live_broker_order_mapping")
            mappings = cursor.fetchone()[0]
            cursor.execute("SELECT count(*) FROM live_broker_order")
            orders = cursor.fetchone()[0]
            cursor.execute("SELECT count(*) FROM live_broker_fill")
            fills = cursor.fetchone()[0]
            cursor.execute("""INSERT INTO daily_strategy_live_trade
                              (strategy_id,paper_trade_id,operation_id,capital_epoch_no,allocated_amount,trade_status)
                              VALUES (%s,%s,%s,1,1000,'CLOSED') RETURNING live_trade_id""",
                           (strategy_id, paper_trade_id, operation_id))
            live_trade_id = int(cursor.fetchone()[0])
        settlement = SettlementAmounts(Decimal("1000"), Decimal("1120"), buy_fee=Decimal("5"), sell_fee=Decimal("5"), sell_tax=Decimal("10"))
        settled_once = store.apply_settlement(live_trade_id=live_trade_id, strategy_id=str(strategy_id), capital_epoch_no=1,
                                              amounts=settlement, settled_at=datetime(2026, 8, 24, 15, 30))
        settled_twice = store.apply_settlement(live_trade_id=live_trade_id, strategy_id=str(strategy_id), capital_epoch_no=1,
                                               amounts=settlement, settled_at=datetime(2026, 8, 24, 15, 30))
        with connection.cursor() as cursor:
            cursor.execute("SELECT strategy_compound_capital,cumulative_net_realized_pnl FROM daily_strategy_compound_capital WHERE strategy_id=%s AND capital_epoch_no=1", (strategy_id,))
            compound, pnl = cursor.fetchone()
        connection.rollback()
    print(json.dumps({"first": first[1], "restart_duplicate": duplicate[1], "second": second[1],
                      "skip": skip[1], "skip_retry": skip_retry[1], "intents": intents, "reservations": reservations,
                      "skips": skips, "settled_once": settled_once, "settled_twice": settled_twice,
                      "compound_capital": str(compound), "net_pnl": str(pnl), "broker_mapping": mappings,
                      "broker_orders": orders, "broker_fills": fills, "rollback": True}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
