SET TIME ZONE 'Asia/Seoul';
CREATE TABLE IF NOT EXISTS analysis_multi_ma_state (
 stock_code VARCHAR(20) NOT NULL, market_code VARCHAR(20) NOT NULL DEFAULT 'KOSPI', trading_venue VARCHAR(10) NOT NULL, strategy_code VARCHAR(30) NOT NULL,
 observation_code VARCHAR(10) NOT NULL, analysis_slot VARCHAR(10) NOT NULL, ma_config_code VARCHAR(100) NOT NULL, price_field_code VARCHAR(100) NOT NULL,
 trade_date DATE, last_processed_time TIMESTAMP(3), position_direction VARCHAR(10) NOT NULL DEFAULT 'FLAT', position_weight NUMERIC(8,6) NOT NULL DEFAULT 0,
 applied_signals JSONB NOT NULL DEFAULT '[]'::jsonb, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(stock_code, market_code, trading_venue, strategy_code, analysis_slot, ma_config_code, price_field_code));
CREATE TABLE IF NOT EXISTS analysis_multi_ma_signal (
 signal_id BIGSERIAL PRIMARY KEY, trade_date DATE NOT NULL, stock_code VARCHAR(20) NOT NULL, trading_venue VARCHAR(10) NOT NULL, strategy_code VARCHAR(30) NOT NULL, observation_code VARCHAR(10) NOT NULL CHECK (observation_code IN ('SEC_05','SEC_10','SEC_15','SEC_20','SEC_25','SEC_30','SEC_35','SEC_40','SEC_45','SEC_50','SEC_55','COMPLETE')), ma_config_code VARCHAR(100) NOT NULL, price_field_code VARCHAR(100) NOT NULL, signal_time TIMESTAMP(3) NOT NULL, signal_no VARCHAR(20) NOT NULL, direction VARCHAR(10) NOT NULL, signal_price NUMERIC(18,2) NOT NULL, reason VARCHAR(500) NOT NULL, created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(trade_date,stock_code,trading_venue,strategy_code,observation_code,ma_config_code,price_field_code,signal_time,signal_no,direction));
CREATE TABLE IF NOT EXISTS analysis_multi_ma_trade (
 trade_id BIGSERIAL PRIMARY KEY, trade_date DATE NOT NULL, stock_code VARCHAR(20) NOT NULL, trading_venue VARCHAR(10) NOT NULL, strategy_code VARCHAR(30) NOT NULL, observation_code VARCHAR(10) NOT NULL, ma_config_code VARCHAR(100) NOT NULL, price_field_code VARCHAR(100) NOT NULL, cycle_no INTEGER NOT NULL, direction VARCHAR(10) NOT NULL, entry_time TIMESTAMP(3) NOT NULL, entry_price NUMERIC(18,2) NOT NULL, entry_ratio NUMERIC(8,6) NOT NULL, average_entry_price NUMERIC(18,6) NOT NULL, exit_time TIMESTAMP(3), exit_price NUMERIC(18,2), exit_type VARCHAR(20), exit_reason VARCHAR(30), realized_profit_amount NUMERIC(22,6), realized_profit_rate NUMERIC(18,10), status VARCHAR(10) NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','CLOSED')), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(trade_date,stock_code,trading_venue,strategy_code,observation_code,ma_config_code,price_field_code,cycle_no));
CREATE TABLE IF NOT EXISTS analysis_multi_ma_trade_leg (trade_id BIGINT NOT NULL REFERENCES analysis_multi_ma_trade(trade_id), signal_no VARCHAR(20) NOT NULL, signal_time TIMESTAMP(3) NOT NULL, entry_price NUMERIC(18,2) NOT NULL, entry_ratio NUMERIC(8,6) NOT NULL, notional_amount NUMERIC(22,6), created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(trade_id,signal_no));
CREATE TABLE IF NOT EXISTS analysis_multi_ma_summary (trade_date DATE NOT NULL, stock_code VARCHAR(20) NOT NULL, trading_venue VARCHAR(10) NOT NULL, strategy_code VARCHAR(30) NOT NULL, observation_code VARCHAR(10) NOT NULL, ma_config_code VARCHAR(100) NOT NULL, price_field_code VARCHAR(100) NOT NULL, initial_capital NUMERIC(22,2) NOT NULL, total_profit_amount NUMERIC(22,6) NOT NULL DEFAULT 0, total_profit_rate NUMERIC(18,10) NOT NULL DEFAULT 0, trade_count INTEGER NOT NULL DEFAULT 0, win_count INTEGER NOT NULL DEFAULT 0, loss_count INTEGER NOT NULL DEFAULT 0, win_rate NUMERIC(18,10) NOT NULL DEFAULT 0, signal_exit_count INTEGER NOT NULL DEFAULT 0, session_close_exit_count INTEGER NOT NULL DEFAULT 0, signal_exit_profit NUMERIC(22,6) NOT NULL DEFAULT 0, session_close_exit_profit NUMERIC(22,6) NOT NULL DEFAULT 0, max_profit NUMERIC(22,6), max_loss NUMERIC(22,6), calculated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(trade_date,stock_code,trading_venue,strategy_code,observation_code,ma_config_code,price_field_code));
